### ISSUE TITLE
LookupError: gradient registry has no entry for: Eig

### ISSUE THREAD

**Issue by mark914** [andrewtuma/HankelDLDMD#1]
dear author：
this is a great work.
but when I run the Train_Pendulum.py， I get an error:
LookupError: gradient registry has no entry for: Eig

I want to ask :The intermediate dmd algorithm has no back propagation，how to fix this problem？

**Comment by mark914** [comment]
thanks，I solve it by changing the gpu（2080 to 3090）

**Comment by andrewtuma** [comment]
@mark914 I am glad that you were able to solve the GPU issue. 

I am not sure what you mean when saying the DMD algorithm has no back propagation? The DMD algorithm contributes to the loss function via "dmdloss" in line 154 of dldmd.py. From there, the loss is used when computing gradients in training.py from lines 49-56, where the gradients are taken from the gradient tape and then used in the method "apply_gradients()" to accomplish backprop.
